### ISSUE TITLE
Java backend: remaining compile errors in dicts, lists, tuples app tests

### ISSUE THREAD

**Issue by ldayton** [ldayton/Tongues#316]
After fixing precedence, assertion, and harness issues (#313), 6 Java app tests still fail. Three are timeouts caused by #315 (liveness bug). The other three are compile errors:

## `apptest_dicts` (8 errors)

| Error | Line | Cause |
|---|---|---|
| `Set<Entry>` cannot convert to `List<List<Object>>` | 178 | `dict.items()` emits `entrySet()` — wrong return type |
| inference variable `K#1` incompatible bounds | 333, 340 | `zip` → `Collectors.toMap` with mixed-type `Arrays.asList` |
| cannot infer type args for `HashMap<>` | 440 | `Map.of(1, "int")` → `Integer` key, target is `Double` key |
| `_popItem` cannot be applied | 494, 497 | `_popItem` expects `LinkedHashMap`, passed `HashMap` |
| illegal start of type | 521 | `HashMap<String, void>` — void as generic type param |
| inference variable `T` incompatible bounds | 550 | zip type inference |

## `apptest_lists` (5 errors)

| Error | Line | Cause |
|---|---|---|
| invalid method reference | 402 | `new ArrayList<>().stream().mapToInt(Integer::intValue)` — empty list, no type |
| inference variable `T` incompatible bounds | 492, 499 | `zip` with mixed `Integer`/`String` in `Arrays.asList` |
| bad operand types for `>` | 807, 850 | `any()` comprehension over `new ArrayList<>()` — untyped `var x > 0` |

## `apptest_tuples` (13 errors)

| Error | Line | Cause |
|---|---|---|
| invalid method reference | 276 | Same empty list + `Integer::intValue` issue |
| cannot find symbol `.get()` | 335, 336 | `t.get(0).get(0)` — `Object` has no `.get()`, needs `(List)` cast |
| inference variable incompatible | 385, 393, 400 | zip type inference |
| bad operand types for `<` | 537 | `list < list` — Java has no `<` for lists, needs comparator |
| cannot find symbol `tuple` | 590, 591 | `isinstance(t, tuple)` → `tuple` isn't a Java type, should map to `List` |
| unexpected type | 592 | Cast to nonexistent `tuple` type |
| cannot infer type args for `ArrayList<>` | 620, 622 | `List<Object>` sublist → `List<Integer>` inference failure |

## Root causes (grouped)

1. **Empty collection type inference** — `new ArrayList<>()` in expression context where Java can't infer the element type (5 occurrences)
2. **zip mixed-type bounds** — `Arrays.asList(a.get(i), b.get(i))` with different types fails `Collectors.toList()`/`toMap()` inference (4 occurrences)
3. **dict.items() type** — `entrySet()` returns `Set<Entry>` not `List<List>` (1)
4. **void as generic param** — `HashMap<String, void>` from None-valued dicts (1)
5. **tuple comparison** — Java lists don't support `<`/`>` operators (1)
6. **tuple isinstance** — `tuple` type name not mapped to `List` in Java (2)
7. **Nested Object access** — `.get().get()` on `Object` needs intermediate cast (2)
8. **HashMap vs LinkedHashMap** — `_popItem` helper signature too narrow (2)
